apiVersion: v1
kind: Secret
metadata:
  name: orderpay-secrets
  namespace: orderpay
type: Opaque
stringData:
  sa-password: "Mauri@22"
  connection-string: "Server=sqlserver,1433;Database=OrderPayDb;User Id=sa;Password=Mauri@22;TrustServerCertificate=True;"
  seq-admin-password: "Mauri@22"
  postgres-password: "Mauri@22"
  keycloak-admin-password: "Mauri@22"
  nextauth-secret: "BRASIL-HEXA-CAMPEAO-DO-MUNDO"
  keycloak-client-secret: "change-me-keycloak-orderpay-web-client-secret"
  rabbitmq-user: "orderpay"
  rabbitmq-password: "Mauri@22"
